dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('inventory', include('inventory.urls')),
]

inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="inventoryhome"),
    path('productcreate', views.createproduct, name="createproduct"),
    path('productlist', views.productlist, name="productlist"),
]

myapp/urls.py
from django.urls import path, include

from myapp.views import * 

from . import views 

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name="home"),
    path('employee', views.employee, name="employee"),
    path('employeelist/', views.employeelist, name="employeelist"),
    path('createuser', views.createuser, name="createuser"),
    path('employeedelete/<int:pk>/', views.employeedelete, name="employeedelete"),
    # path('employeedelete/<int:pk>', EmployeedeleteView.as_view(), name="employeedelete"),
    path('loginpage', views.loginpage, name="login"),
    path('applyleave', views.applyleave, name="applyleave"),
    path('payroll/', views.payroll, name="payroll"),

    path('logout', views.logoutUser, name='logoutuser'),
    
]

inventory/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    


class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    product_name = models.CharField(max_length=150)
    description = models.CharField(max_length=350)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/products/')

    def __str__(self):
        return self.product_name


    

myapp/models.py
from django.db import models

# Create your models here.


class EmployeeDetails(models.Model):
    employee_name = models.CharField(max_length=150)
    address = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    designation = models.CharField(max_length=100)
    salary = models.IntegerField(default=0)

    def __str__(self):
        return self.email






    

inventory/views.py
from django.shortcuts import render

from inventory.models import * 

# Create your views here.

def index(request):
    product = Product.objects.all()

    product_count = Product.objects.all().count()

    products = {
        'products' : product,
        'product_count' : product_count,
    }
    return render(request, 'inventoryhome.html', products)

def productlist(request):
    product = Product.objects.all()

    products = {
        'products' : product,
    }
    return render(request, 'inventorylist.html', products)


def createproduct(request):
    if request.method == "POST":
        category = request.POST.get('category')
        print(request.POST)

    return render(request, 'createproduct.html')

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from myapp.models import * 

# Create your views here.

def index(request):
    username = request.user.username
    print(username)
    return render(request, 'index.html', {'username': username})



def employee(request):
    employee_details = EmployeeDetails.objects.all()
    total_employee = EmployeeDetails.objects.all().count()

    print(total_employee)
    
    emp_data = {
        'total_employee' : total_employee,
        'employee_details': employee_details,

    }


    # return render(request, 'employee.html', {'employee_details' : employee_details })
    return render(request, 'employee.html', emp_data)


def employeelist(request):
    employee_details = EmployeeDetails.objects.all()

    return render(request, 'employeelist.html', {'employee_details': employee_details})


def createuser(request):

    if request.method == "POST":
        name = request.POST.get('name')
        address = request.POST.get('address')
        print(address)
        email = request.POST.get('email')
        designation = request.POST.get('designation')
        salary = request.POST.get('salary')

        createuser= EmployeeDetails(employee_name=name, address=address, email=email, designation=designation, salary= salary)
        print(createuser)
        createuser.save()

    return render(request, 'createuser.html')

def loginpage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username= username, password = password)

        if user is not None:
            login(request, user)
            return redirect('myapp:home')
        else:
            return render(request, 'login.html')
    return render(request, 'login.html')


def employeedelete(request, pk):

    eid = EmployeeDetails.objects.get(id=pk)
    print(eid, "EID")

    context = {
        'items' : eid,
    }

    if request.method == "POST":
        eid.delete()


    return render(request, 'employeelist.html', context)

def applyleave(request):
    return render(request, 'application.html')

def payroll(request):
    
    return render(request, 'payroll.html')


def logoutUser(request):
    logout(request)
    return redirect('myapp:login')

templates/base.html
<!DOCTYPE html>

{% load static %}


<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

    <title>Gusto DASHBOARD</title>
  </head>

  <body>
{% block body %}


{% endblock body %}

<div id="sidebar">
        <div class="sidebar__title">
          <div class="sidebar__img">
            <h1>Gusto Info Sys</h1>
          </div>
          <i
            onclick="closeSidebar()"
            class="fa fa-times"
            id="sidebarIcon"
            aria-hidden="true"
          ></i>
        </div>

        <!-- Side Bar -->

        <div class="sidebar__menu">
          <div class="sidebar__link active_menu_link">
            <i class="fa fa-home"></i>
            <a href="/">Dashboard</a>
          </div>
          <h2>Gusto Dashboard</h2>
          <div class="sidebar__link">
            <i class="fa fa-building-o"></i>
            <a href="{% url 'myapp:employee' %}">Employee Management</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-archive"></i>
            <a href="{% url 'inventoryhome'%}">Inventory Management</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-handshake-o"></i>
            <a href="#">Contracts</a>
          </div>
          <h2>LEAVE</h2>
          <div class="sidebar__link">
            <i class="fa fa-question"></i>
            <a href="#">Requests</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-sign-out"></i>
            <a href="#">Leave Policy</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-calendar-check-o"></i>
            <a href="#">Special Days</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-files-o"></i>
            <a href="{% url 'myapp:applyleave' %}">Apply for leave</a>
          </div>
          <h2>PAYROLL</h2>
          <div class="sidebar__link">
            <i class="fa fa-money"></i>
            <a href="{% url 'myapp:payroll' %}">Payroll</a>
          </div>
          <div class="sidebar__link">
            <i class="fa fa-briefcase"></i>
            <a href="#">Paygrade</a>
          </div>
          <div class="sidebar__logout">
            <i class="fa fa-power-off"></i>
            <a href="{% url 'myapp:logoutuser' %}">Log out</a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src={% static "script.js"%}></script>
</body>

</html>

templates/createproduct.html
<!-- CSS only -->


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


<form method="POST">
{% csrf_token %}
  <div class="form-group">
    <label>Category</label>
    <input type="text" name="category" class="form-control" placeholder="Category">
  </div>
  <div class="form-group">
    <label>Product Name</label>
    <input type="text" name = "product_name" class="form-control" placeholder="Product Name">
  </div>
  <div class="form-group">
    <label>Description</label>
    <input type="text" name="description" class="form-control" placeholder="Description">
  </div>
  <div class="form-group">
    <label>Price</label>
    <input type="number" name = "price" class="form-control" placeholder="Price">
  </div>
  <div class="form-group">
    <label>Upload Image</label>
    <input type="file" name = "image" class="form-control" placeholder="Image Here">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/createuser.html
<!-- CSS only -->


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


<form method="POST">
{% csrf_token %}
  <div class="form-group">
    <label>Employee Name</label>
    <input type="text" name="name" class="form-control" placeholder="Employee Name">
  </div>
  <div class="form-group">
    <label>Address</label>
    <input type="text" name = "address" class="form-control" placeholder="Address">
  </div>
  <div class="form-group">
    <label>Email</label>
    <input type="email" name="email" class="form-control" placeholder="Email">
  </div>
  <div class="form-group">
    <label>Designation</label>
    <input type="text" name = "designation" class="form-control" placeholder="Designation">
  </div>
  <div class="form-group">
    <label>Salary</label>
    <input type="number" name = "salary" class="form-control" placeholder="Salary">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/delete.html
 
 
<form method="POST" action="{% url 'employeedelete' .pk%}">
    {% csrf_token %}
    <input type ="submit" value="Delete"> 
<form> 

templates/employee.html
{% extends 'base.html' %}


{% load static %}




{% block body %}


  <body id="body">
    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a class="active_link" href="#">Admin</a>
        </div>
        <div class="navbar__right">
          <a href="#">
            <i class="fa fa-search" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </a>
          <a href="#">
            <img width="30" src= "{% static "images/avatar.svg"%}" alt="" />
            <!-- <i class="fa fa-user-circle-o" aria-hidden="true"></i> -->
          </a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="{% static 'images/hello.svg' %}" alt="" />
            <div class="main__greeting">
              <h1>Hello Admin</h1>
              <p>Welcome to your admin dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Total Number of Employee</p>
                <span class="font-bold text-title">{{total_employee}}</span>
              </div>
            </div>

            <div class="card">
              <i class="fa fa-calendar fa-2x text-red" aria-hidden="true"></i>
              <div class="card_inner">
                <!-- -->
                <a href = "/employeelist"><p class="text-primary-p">Employee List</p>
                <span class="font-bold text-title">Click here to view </span></a>
              </div>
            </div>
            <div class="card">
              <i class="fa fa-user-o fa-2x text-lightblue" aria-hidden="true"></i>
              <div class="card_inner">
                <!-- -->
                <a href = "/createuser"><p class="text-primary-p">Create User</p>
                <span class="font-bold text-title">Click here to create Employee </span></a>
              </div>
            </div>
          </div>

  
          <!-- MAIN CARDS ENDS HERE -->

          <!-- CHARTS STARTS HERE -->

          <!-- CHARTS ENDS HERE -->
        </div>
      </main> 
{% endblock body%}

templates/employeelist.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<body id="body">


    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <h1> Employee list </h1>
        <div class="navbar__left">
          <a class="active_link" href="#">Admin</a>
        </div>
        <div class="navbar__right">
          <a href="#">
            <i class="fa fa-search" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </a>
          <a href="#">
            <img width="30" src= "{% static "images/avatar.svg"%}" alt="" />
            <!-- <i class="fa fa-user-circle-o" aria-hidden="true"></i> -->
          </a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="{% static 'images/hello.svg' %}" alt="" />
            <div class="main__greeting">
              <h1>Hello Admin</h1>
              <p>Welcome to your admin dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          {% for employee in employee_details %}
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">{{employee.id}}</p>
                <p class="text-primary-p">{{employee.employee_name}}</p>
                <p class="text-primary-p">{{employee.designation}}</p>


                <form method="POST" action="{% url 'myapp:employeedelete' employee.id %}">
                {% csrf_token %}
                <input type="Submit" value = "Delete">
                {% comment %} <a href = "employeedelete/{{employee.id}}"> Delete </a> {% endcomment %}
                <form>
              </div>
            </div>
            </div>
            {% endfor %}

          <!-- CHARTS ENDS HERE -->
        </div>
      </main> 



{% endblock body %}

templates/index.html
{% extends 'base.html' %}


{% load static %}

{% block body %}


  <body id="body">
    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a href="#">Subscribers</a>
          <a href="#">Video Management</a>
          <a class="active_link" href="#">Admin</a>
        </div>
        <div class="navbar__right">
          <a href="#">
            <i class="fa fa-search" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </a>
          <a href="#">
            <img width="30" src= "{% static "images/avatar.svg"%}" alt="" />
            <!-- <i class="fa fa-user-circle-o" aria-hidden="true"></i> -->
          </a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="{% static 'images/hello.svg' %}" alt="" />
            <div class="main__greeting">
              <h1>Hello {{username}}</h1>
              <p>Welcome to your admin dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Subscribers</p>
                <span class="font-bold text-title">578</span>
              </div>
            </div>

            <div class="card">
              <i class="fa fa-calendar fa-2x text-red" aria-hidden="true"></i>
              <div class="card_inner">
                <!-- -->
                <p class="text-primary-p">Times of Watching</p>
                <span class="font-bold text-title">2467</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-video-camera fa-2x text-yellow"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Videos</p>
                <span class="font-bold text-title">340</span>
              </div>
            </div>

            <div class="card">
              <i
                class="fa fa-thumbs-up fa-2x text-green"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Number of Likes</p>
                <span class="font-bold text-title">645</span>
              </div>
            </div>
          </div>
          <!-- MAIN CARDS ENDS HERE -->

          <!-- CHARTS STARTS HERE -->
          <div class="charts">
            <div class="charts__left">
              <div class="charts__left__title">
                <div>
                  <h1>Daily Reports</h1>
                  <p>Cupertino, California, USA</p>
                </div>
                <i class="fa fa-usd" aria-hidden="true"></i>
              </div>
              <div id="apex1"></div>
            </div>

            <div class="charts__right">
              <div class="charts__right__title">
                <div>
                  <h1>Stats Reports</h1>
                  <p>Sallaghari, Kathmandu, Nepal</p>
                </div>
                <i class="fa fa-usd" aria-hidden="true"></i>
              </div>

              <div class="charts__right__cards">
                <div class="card1">
                  <h1>Income</h1>
                  <p>$75,300</p>
                </div>

                <div class="card2">
                  <h1>Sales</h1>
                  <p>$124,200</p>
                </div>

                <div class="card3">
                  <h1>Users</h1>
                  <p>3900</p>
                </div>

                <div class="card4">
                  <h1>Orders</h1>
                  <p>1881</p>
                </div>
              </div>
            </div>
          </div>
          <!-- CHARTS ENDS HERE -->
        </div>
      </main> 
{% endblock body%}

templates/inventoryhome.html
{% extends 'base.html' %}


{% load static %}




{% block body %}


  <body id="body">
    <div class="container">
      <nav class="navbar">
      <h2> Inventory Home </h2>
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a class="active_link" href="#">Admin</a>
        </div>
        <div class="navbar__right">
          <a href="#">
            <i class="fa fa-search" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </a>
          <a href="#">
            <img width="30" src= "{% static "images/avatar.svg"%}" alt="" />
            <!-- <i class="fa fa-user-circle-o" aria-hidden="true"></i> -->
          </a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="{% static 'images/hello.svg' %}" alt="" />
            <div class="main__greeting">
              <h1>Hello Admin</h1>
              <p>Welcome to your admin dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">Products</p>
                <span class="font-bold text-title">{{product_count}}</span>
              </div>
            </div>

            <div class="card">
              <i class="fa fa-calendar fa-2x text-red" aria-hidden="true"></i>
              <div class="card_inner">
                <!-- -->
                <a href = "{% url 'productlist' %}"><p class="text-primary-p">Product List </p>
                <span class="font-bold text-title">Click here to view list </span></a>
              </div>
            </div>
            <div class="card">
              <i class="fa fa-user-o fa-2x text-lightblue" aria-hidden="true"></i>
              <div class="card_inner">
                <!-- -->
                <a href = "{% url 'createproduct' %}"><p class="text-primary-p">Add Product</p>
                <span class="font-bold text-title">Click here to Add Product </span></a>
              </div>
            </div>
          </div>

          <!-- MAIN CARDS ENDS HERE -->

          <!-- CHARTS STARTS HERE -->

          <!-- CHARTS ENDS HERE -->
        </div>
      </main> 
{% endblock body%}

templates/inventorylist.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<body id="body">


    <div class="container">
      <nav class="navbar">
        <div class="nav_icon" onclick="toggleSidebar()">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </div>
        <div class="navbar__left">
          <a href="#">Subscribers</a>
          <a href="#">Video Management</a>
          <a class="active_link" href="#">Admin</a>
        </div>
        <div class="navbar__right">
          <a href="#">
            <i class="fa fa-search" aria-hidden="true"></i>
          </a>
          <a href="#">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </a>
          <a href="#">
            <img width="30" src= "{% static "images/avatar.svg"%}" alt="" />
            <!-- <i class="fa fa-user-circle-o" aria-hidden="true"></i> -->
          </a>
        </div>
      </nav>

      <main>
        <div class="main__container">
          <!-- MAIN TITLE STARTS HERE -->

          <div class="main__title">
            <img src="{% static 'images/hello.svg' %}" alt="" />
            <div class="main__greeting">
              <h1>Hello Admin</h1>
              <p>Welcome to your admin dashboard</p>
            </div>
          </div>

          <!-- MAIN TITLE ENDS HERE -->

          <!-- MAIN CARDS STARTS HERE -->
          {% for product in products %}
          <div class="main__cards">
            <div class="card">
              <i
                class="fa fa-user-o fa-2x text-lightblue"
                aria-hidden="true"
              ></i>
              <div class="card_inner">
                <p class="text-primary-p">{{product.product_name}}</p>
                <p class="text-primary-p">{{product.price}}</p>
              </div>
            </div>
            </div>
            {% endfor %}


            
          <!-- CHARTS ENDS HERE -->
        </div>
      </main> 



{% endblock body %}

templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">

                        {% csrf_token %}

						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
			</div>
		</div>
	</div>
</body>

</html>